services:
  - name: my-flask-app
    type: web
    runtime: python
    plan: free
    envVars:
      - key: PORT
        value: 10000
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
